config/routes.rb
Rails.application.routes.draw do
 
  resources :users, only: [:new, :create, :index]

  resources :sessions, only: [:new, :create, :destroy]

  resources :projects do
    resources :comments, only: [:create]
    patch :change_status, on: :member
  end
  

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  root 'projects#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :project
  belongs_to :user  # Assuming each comment is linked to a user
  validates :body, presence: true  # Validate that body cannot be blank
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :status_changes, dependent: :destroy

  # Define available statuses (example)
  STATUSES = ['open', 'in_progress', 'completed', 'archived']
end

app/models/status_change.rb
class StatusChange < ApplicationRecord
  belongs_to :project
  belongs_to :user

  validates :previous_status, presence: true
  validates :new_status, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :projects
    has_many :comments
    has_many :status_changes
  
    validates :email, presence: true, uniqueness: true
    validates :password, presence: true
  end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user
  
    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
  
    def logged_in?
      !!current_user
    end
  
    # You can add a method to protect certain actions if needed
    def require_user
      redirect_to login_path unless logged_in?
    end
  end
  

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :set_project
  
    def create
      @comment = @project.comments.build(comment_params)
      @comment.user = current_user
  
      if @comment.save
        redirect_to @project, notice: 'Comment added successfully.'
      else
        redirect_to @project, alert: 'Failed to add comment.'
      end
    end
  
    private
  
    def set_project
      @project = Project.find(params[:project_id])
    end
  
    def comment_params
      params.require(:comment).permit(:body)
    end
  end
  

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :require_user, only: [:new, :create, :edit, :update, :change_status]
  before_action :set_project, only: [:show, :edit, :update, :change_status]

  def index
    @projects = Project.all
  end
  
  def show
    @comments = @project.comments.includes(:user) # Preload associated users
    @status_changes = @project.status_changes.includes(:user) # Preload associated users for status changes
  end
  
  

  def new
    @project = Project.new
  end

  def create
    @project = current_user.projects.new(project_params)
    if @project.save
      redirect_to @project, notice: 'Project created successfully'
    else
      render :new
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    if @project.update(project_params)
      redirect_to @project, notice: 'Project updated successfully.'
    else
      render :edit
    end
  end

  def destroy
    @project = Project.find_by(id: params[:id])
    if @project
      @project.destroy
      redirect_to projects_path, notice: 'Project was successfully deleted.'
    else
      redirect_to projects_path, alert: 'Project not found.'
    end
  end
  
  def change_status
    @project = Project.find(params[:id])
    previous_status = @project.status
  
    if @project.update(status: params[:status])
      StatusChange.create!(
        project: @project,
        user: current_user,
        previous_status: previous_status,
        new_status: @project.status
      )
      redirect_to @project, notice: 'Project status updated successfully.'
    else
      redirect_to @project, alert: 'Failed to update status.'
    end
  end
  
  private

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:title, :description, :status)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
      # renders login form
    end
    
    def create
      user = User.find_by(email: params[:email])
      if user&.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to projects_path, notice: 'Logged in successfully'
      else
        flash.now[:alert] = 'Invalid email or password'
        render :new
      end
    end
  
    def destroy
      session[:user_id] = nil
      redirect_to login_path, notice: 'Logged out successfully'
    end
  end
  

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index
      @users = User.all
    end

  
    def new
      @user = User.new
    end
  
    def create
      @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id
        redirect_to projects_path, notice: 'Account created successfully'
      else
        render :new
      end
    end
  
    private
  
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project Conversations</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <div class="container">
    
    <!-- Navigation Bar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>

      <div class="collapse navbar-collapse">
        <ul class="navbar-nav ml-auto">
          <% if session[:user_id] %> <!-- Check if the user is logged in -->
            <li class="nav-item">
              <%= link_to 'Logout', logout_path, method: :delete, data: { confirm: 'Are you sure?' }, class: 'nav-link' %>
            </li>
          <% else %> <!-- If not logged in, show login link -->
            <li class="nav-item">
              <%= link_to 'Login', login_path, class: 'nav-link' %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

    <!-- Flash Messages -->
    <% flash.each do |key, message| %>
      <div class="alert alert-<%= key == 'notice' ? 'info' : key %>">
        <%= message %>
      </div>
    <% end %>
    
    <!-- Main Content -->
    <%= yield %>
  </div>

  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>

<%= form_with model: @project, local: true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :status %>
    <%= f.select :status, Project::STATUSES, {}, class: 'form-control' %>
  </div>

  <%= f.submit 'Update Project', class: 'btn btn-primary' %>
<% end %>

app/views/projects/index.html.erb
<h1>Projects</h1>
<%= link_to 'New Project', new_project_path, class: 'btn btn-primary' %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Status</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to project.title, project %></td>
        <td><%= project.description %></td>
        <td><%= project.status %></td>
        <td>
          <%= link_to 'Edit', edit_project_path(project), class: 'btn btn-warning' %>
          <%= link_to 'Delete', project, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= form_with model: @project do |form| %>
  <% if @project.errors.any? %>
    <div class="alert alert-danger">
      <h4>The following errors prevented the project from being saved:</h4>
      <ul>
        <% @project.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :status %>
    <%= form.select :status, ['Pending', 'In Progress', 'Completed'], {}, class: 'form-control' %>
  </div>

  <%= form.submit 'Create Project', class: 'btn btn-primary' %>
<% end %>

<%= link_to 'Back', projects_path, class: 'btn btn-secondary' %>

app/views/projects/show.html.erb
<h1><%= @project.title %></h1>
<p><%= @project.description %></p>
<p>Status: <%= @project.status %></p>

<h2>Conversation History</h2>
<ul class="list-group">
  <% if @comments.any? %>
    <% @comments.each do |comment| %>
      <li class="list-group-item">
        <strong><%= comment.user.name %>:</strong> <%= comment.body %>
      </li>
    <% end %>
  <% else %>
    <li class="list-group-item">No comments yet.</li>
  <% end %>

  <% if @status_changes.any? %>
    <% @status_changes.each do |status_change| %>
      <li class="list-group-item">
        <strong>Status changed by <%= status_change.user.name %>:</strong> 
        from "<%= status_change.previous_status %>" to "<%= status_change.new_status %>"
      </li>
    <% end %>
  <% else %>
    <li class="list-group-item">No status changes yet.</li>
  <% end %>
</ul>

<h3>Add Comment</h3>
<%= form_with model: [@project, @project.comments.build], local: true do |f| %>
  <div class="form-group">
    <%= f.text_area :body, class: 'form-control', placeholder: 'Add a comment...' %>
  </div>
  <%= f.submit 'Add Comment', class: 'btn btn-primary' %>
<% end %>

<h3>Change Status</h3>
<%= form_with url: change_status_project_path(@project), method: :patch, local: true do |f| %>
  <div class="form-group">
    <%= f.label :status, 'Select Status' %>
    <%= f.select :status, Project::STATUSES, {}, class: 'form-control' %>
  </div>
  <%= f.submit 'Change Status', class: 'btn btn-primary' %>
<% end %>
<%= link_to 'Delete Project', @project, method: :delete, data: { confirm: 'Are you sure you want to delete this project?' }, class: 'btn btn-danger' %>


<%= link_to 'Back to Projects', projects_path, class: 'btn btn-secondary' %>

app/views/users/index.html.erb
<h1>All Users</h1>

<ul>
  <% @users.each do |user| %>
    <li><%= user.name %> - <%= user.email %></li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_with(model: @user, local: true) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.email_field :email, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :password %>
    <%= form.password_field :password, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.submit "Register", class: 'btn btn-primary' %>
  </div>
<% end %>